# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
#
trigger: none
pr: none

schedules:
- cron: "55 01 * * *"
  displayName: Daily build
  branches:
    include:
    - master
  always: true

pool: Self Hosted Pool

variables:
  tag: '$(Build.BuildId)'
  dockerfile: '$(Build.SourcesDirectory)/Dockerfile'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    timeoutInMinutes: 0
    displayName: Build
    steps:
    - script: |
        echo $(pwd)
        ls | xargs echo
      displayName: 'Docker Build'
