# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
#
trigger: none
pr: none

schedules:
- cron: "56 05 * * *"
  displayName: Daily build
  branches:
    include:
    - master
  always: true

pool: Self Hosted Pool

variables:
  tag: '$(Build.BuildId)'
  dockerfile: '$(Build.SourcesDirectory)/Dockerfile'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    timeoutInMinutes: 0
    displayName: Build
    steps:
    - script: |
        echo $(pwd)
        echo ls -l > /home/itokawa/aaaaa.log
      displayName: 'Docker Build'
    
- stage: Deploy
  jobs:
    # track deployments on the environment
  - deployment: Deploy
    environment: 'yocto-dev'
    strategy:
      # default deployment strategy
      runOnce:
        deploy:
          steps:
          - script: cp /datadrive/poky/build/tmp/deploy/images/qemux86/core-image-minimal-qemux86-20200718051321.qemuboot.conf /home/itokawa/
            displayName: 'Deploy Images'
