# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerfile: '$(Build.SourcesDirectory)/Dockerfile'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    timeoutInMinutes: 0
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
#
#    - task: Docker@2
#
#      displayName: Build an image
#
#      inputs:
#
#        command: build
#
#        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
#
#        tags: |
#
#          $(tag)
#
    - script: |
        docker build -f $(dockerfile) -t yocto:latest .
        git config --global user.email "experiment@gyz.co.jp"
        git config --global user.name "itokawaa"
        git clone git://git.yoctoproject.org/poky
        cd poky
        git fetch --tags
        git checkout tags/yocto-2.7 -b my-yocto-2.7
        docker run --rm \
            -u $(id -u):$(id -g) \
            -v $(pwd):$(pwd) \
            -w $(pwd) \
            yocto:latest \
            /bin/bash -c 'source oe-init-build-env &&  bitbake core-image-sato'
