# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
#
trigger:
- master

pool: Self Hosted Pool

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    timeoutInMinutes: 0
    displayName: Build
    steps:
    - script: |
      echo 'hello!'
      displayName: 'Docker Build'
