# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
#
trigger:
- master

pool: Self Hosted Pool

- script: |
  echo 'hello!'
  displayName: 'Docker Build'
