# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool: Self Hosted Pool

variables:
  tag: '$(Build.BuildId)'
  dockerfile: '$(Build.SourcesDirectory)/Dockerfile'

steps:
- script: |
    docker build -f $(dockerfile) -t yocto:latest .
  displayName: 'Docker Build'
    
- script: |
    cd /datadrive
    git clone git://git.yoctoproject.org/poky
  displayName: 'clone poky'

- script: |
    cd /datadrive/poky
    git fetch --tags
    git checkout tags/yocto-2.7 -b my-yocto-2.7
    docker run --rm \
        -u $(id -u):$(id -g) \
        -v $(pwd):$(pwd) \
        -w $(pwd) \
        yocto:latest \
        /bin/bash -c 'source oe-init-build-env &&  bitbake core-image-sato'
  displayName: 'execute bitbake'
